# Generated by Django 3.2.9 on 2022-08-30 22:34

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='product/product.png', storage=user.models.OverwriteStorage(), upload_to=user.models.image_upload)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('black', 'black')], max_length=10)),
                ('size', models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('suitable', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('all', 'all')], max_length=5)),
                ('main_image', models.ImageField(default='product/product.png', storage=user.models.OverwriteStorage(), upload_to=user.models.image_upload)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('selled', models.PositiveIntegerField(default=0)),
                ('image', models.ManyToManyField(blank=True, to='product.ProductImage')),
                ('product_info', models.ManyToManyField(blank=True, to='product.ProductInfo')),
            ],
        ),
    ]
