# Generated by Django 3.2.9 on 2022-08-31 01:06

from django.db import migrations, models
import product.models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220831_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='product/product.png', storage=user.models.OverwriteStorage(), upload_to=product.models.image_upload),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(default='product/product.png', storage=user.models.OverwriteStorage(), upload_to=product.models.image_upload, validators=[product.models.image_upload]),
        ),
    ]
