# Generated by Django 3.2.9 on 2022-08-31 01:23

from django.db import migrations, models
import product.models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='product/product.png', storage=user.models.OverwriteStorage(), upload_to=user.models.image_upload, validators=[product.models.validate_dimension]),
        ),
    ]
