# Generated by Django 3.2.9 on 2022-09-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220911_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size1',
            field=models.CharField(max_length=50),
        ),
    ]
