# Generated by Django 3.2.9 on 2022-09-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220911_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color1',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='size1',
            field=models.CharField(default='m', max_length=50),
            preserve_default=False,
        ),
    ]
