# Generated by Django 3.2.9 on 2022-09-15 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220911_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_dis',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
