# Generated by Django 3.2.9 on 2022-09-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_price_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
