# Generated by Django 3.2.9 on 2022-09-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220918_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='color1',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color2',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color3',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color4',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color5',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size1',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size2',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size3',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size4',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size5',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size6',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='suitable',
            field=models.CharField(choices=[('All-Gender', 'All-Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Baby', 'Baby')], max_length=20),
        ),
    ]
