# Generated by Django 3.2.9 on 2022-09-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220922_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Swimwear', 'Swimwear'), ('Sleepwear', 'Sleepwear'), ('Sportswear', 'Sportswear'), ('Jumpsuits', 'Jumpsuits'), ('Blazers', 'Blazers'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes')], max_length=50),
        ),
    ]
