# Generated by Django 3.2.9 on 2022-10-15 20:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import product.models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Swimwear', 'Swimwear'), ('Sleepwear', 'Sleepwear'), ('Sportswear', 'Sportswear'), ('Jumpsuits', 'Jumpsuits'), ('Blazers', 'Blazers'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color1',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True, verbose_name='color 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color2',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True, verbose_name='color 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color3',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True, verbose_name='color 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color4',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True, verbose_name='color 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color5',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20, null=True, verbose_name='color 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, to='product.ProductImage', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='product/product.png', storage=user.models.OverwriteStorage(), upload_to=user.models.image_upload, validators=[product.models.validate_dimension], verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_dis',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price before discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selled',
            field=models.PositiveIntegerField(default=0, verbose_name='selled'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size1',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True, verbose_name='size 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size2',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True, verbose_name='size 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size3',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True, verbose_name='size 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size4',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True, verbose_name='size 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size5',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True, verbose_name='size 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size6',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True, verbose_name='size 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suitable',
            field=models.CharField(choices=[('All-Gender', 'All-Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Baby', 'Baby')], max_length=20, verbose_name='suitable'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(default='product/product.png', storage=user.models.OverwriteStorage(), upload_to=user.models.image_upload, validators=[product.models.validate_dimension], verbose_name='image'),
        ),
    ]
