# Generated by Django 3.2.9 on 2022-10-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
    ]
