# Generated by Django 4.1 on 2022-12-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_statics_alter_colormodel_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='statics',
            options={'verbose_name': 'Statics', 'verbose_name_plural': 'Statics'},
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='product.colormodel', verbose_name='colors'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='product.sizemodel', verbose_name='sizes'),
        ),
    ]
