# Generated by Django 4.1 on 2022-12-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_comment_options_alter_statics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colormodel',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
