# Generated by Django 3.2.9 on 2022-10-03 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonuserorder',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonuserorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonuserorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nonuserorder',
            name='track',
            field=models.CharField(choices=[('Not-Charged', 'Not-Charged'), ('On-way', 'On-way'), ('Delivered', 'Delivered')], default='Not-Charged', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.CharField(choices=[('Not-Charged', 'Not-Charged'), ('On-way', 'On-way'), ('Delivered', 'Delivered')], default='Not-Charged', max_length=20),
        ),
    ]
