# Generated by Django 3.2.9 on 2022-10-04 00:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_auto_20221004_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonuserorder',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='nonuserorder',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='nonuserorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nonuserorder',
            name='track',
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01xx xxx xxxx'. Up to 11 digits allowed.", regex='[0][1][0125][0-9][ ]?\\d{3}[ ]?\\d{4}')])),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('add1', models.CharField(max_length=50)),
                ('add2', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('orders', models.ManyToManyField(blank=True, to='cart.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
