# Generated by Django 3.2.9 on 2022-10-04 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20221004_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
