# Generated by Django 3.2.9 on 2022-10-15 20:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20221015_2229'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0007_auto_20221015_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='add1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address 1'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='add2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address 2'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='orders',
            field=models.ManyToManyField(blank=True, to='cart.Order', verbose_name='orders'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01xx xxx xxxx'. Up to 11 digits allowed.", regex='[0][1][0125][0-9][ ]?\\d{3}[ ]?\\d{4}')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='nonuserorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='nonuserorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='nonuserorder',
            name='user_cart_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='user cart id'),
        ),
    ]
