# Generated by Django 3.2.9 on 2022-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
