# Generated by Django 3.2.9 on 2022-09-23 21:13

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='', max_length=30, validators=[user.models.validate_name], verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01xx xxx xxxx'. Up to 11 digits allowed.", regex='[0][1][0125][0-9][ ]?\\d{3}[ ]?\\d{4}')]),
            preserve_default=False,
        ),
    ]
