# Generated by Django 3.2.9 on 2022-10-15 20:29

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220923_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255, verbose_name='auth provider'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='user/avatar.png', storage=user.models.OverwriteStorage(), upload_to=user.models.image_upload, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='avatar url'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is verified'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01xx xxx xxxx'. Up to 11 digits allowed.", regex='[0][1][0125][0-9][ ]?\\d{3}[ ]?\\d{4}')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='seller',
            field=models.BooleanField(default=False, verbose_name='seller'),
        ),
    ]
