# Generated by Django 4.1 on 2022-12-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_googleprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
