# Generated by Django 4.1 on 2022-12-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userprofile_youtube_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleprofile',
            options={'verbose_name': 'GoogleProfile', 'verbose_name_plural': 'GoogleProfiles'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.AlterField(
            model_name='googleprofile',
            name='google_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='google id'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('en', 'English')], max_length=20, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_url',
            field=models.URLField(blank=True, null=True, verbose_name='company url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('Alex', 'Alex'), ('Cairo', 'Cairo')], max_length=20, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='facebook url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='instagram url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='langs',
            field=models.ManyToManyField(blank=True, to='user.languages', verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='quora_url',
            field=models.URLField(blank=True, null=True, verbose_name='quora url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='twitter url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='youtube url'),
        ),
    ]
